[package]
name = "xq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xq-derive = { path = "../xq-derive" }
xq-std = { path = "../xq-std" }
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"