[package]
name = "xq-wasm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leb128 = "0.2.4"
anyhow = "1.0.33"

[lib]
crate-type = ["rlib"]