[package]
name = "wasm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime ={version = "9.0.0"}
anyhow = "1.0.42"

[dependencies.statedb]
path = "../statedb"

