[package]
name = "xq-std"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wee_alloc = "0.4.5"

[dependencies.xq-common]
path = "../xq-common"
default-feature = false

[lib]
crate-type = ["rlib"]
