[package]
name = "xq-std"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wee_alloc = "0.4.5"
serde_json = "1.0"
serde = "1.0"

[features]
default = ["std"]
std = []

[lib]
crate-type = ["rlib"]
