[package]
name = "x-db"
description = "X database"
version = "0.1.0"

[dependencies]
rocksdb = { version = "0.19.0", features = ["lz4"] }
anyhow = "1.0.62"
types = {version = "0.1.0", path = "../types"}
crypto = {version = "0.1.0", path = "../crypto"}