[package]
name = "statedb"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty-leveldb = "0.3.6"
lazy_static = "1.4.0"
anyhow = "1.0.42"
parking_lot = "0.12"
